//
//  AWSConfiguration.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.16
//
//

#import "AWSConfiguration.h"



// Cognito User Pools Identity Id
NSString *const AWSCognitoUserPoolId = @"us-west-2_dy5NPpQm3";

// Cognito User Pools App Client Id
NSString *const AWSCognitoUserPoolClientId = @"5ishstos0eirprout3o5r07206";

// Cognito User Pools Client Secret
NSString *const AWSCognitoUserPoolClientSecret = @"1qc5lgr1rihfmtvrhemdp142m1q8l2hnto40pokq5nb1ihmuroop";

// Cognito User Pools Region
AWSRegionType const AWSCognitoUserPoolRegion = AWSRegionUSWest2;
